name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  # Allows to run workflow manually from Actions tab
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Read .env
        id: hugo-version
        run: |
          . ./.env
          echo "HUGO_VERSION=${HUGO_VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '${{ steps.hugo-version.outputs.HUGO_VERSION }}'
          extended: true

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
